[package]
name = "c2pa-python"
version = "0.4.0"
edition = "2021"
authors = ["Gavin Peacock <gpeacock@adobe.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "c2pa"
crate-type = ["cdylib"]

[features]
v1 = ["c2pa/file_io"]

[dependencies]
c2pa = {git = "https://github.com/contentauth/c2pa-rs.git", branch = "main", features = ["unstable_api", "openssl", "openssl_sign"]}
pem = "3.0.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0.49"
uniffi = "0.24.1"

[build-dependencies]
uniffi = { version = "0.24.1", features = ["build"] }
